import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { GlyphDefinition } from '@glyphp/server'
import type { ImportedServer, McpServerConfig } from './types.js'

/**
 * Writes the per-MCP project directory: `server.ts`, `package.json`,
 * `.env.example`, and a README explaining how to run it. The generated
 * server.ts embeds the original stdio command so the consumer doesn't have
 * to remember it.
 */
export async function emitServerProject(
  config: McpServerConfig,
  glyphs: GlyphDefinition<any, any>[],
  port: number,
  outDir: string,
): Promise<ImportedServer> {
  await mkdir(outDir, { recursive: true })

  const cards = glyphs.map((g) => ({
    name: g.card.name,
    riskTier: g.card.cost.riskTier,
    requiresConfirmation: g.card.cost.requiresConfirmation,
  }))

  await writeFile(join(outDir, 'server.ts'), renderServerTs(config, port), 'utf8')
  await writeFile(join(outDir, 'package.json'), renderPackageJson(config), 'utf8')
  await writeFile(join(outDir, '.env.example'), renderEnvExample(config), 'utf8')
  await writeFile(join(outDir, 'README.md'), renderReadme(config, port, cards), 'utf8')

  return {
    config,
    port,
    toolCount: glyphs.length,
    cards,
    outputDir: outDir,
  }
}

function renderServerTs(config: McpServerConfig, port: number): string {
  if (config.transport.kind !== 'stdio') {
    // The importer rejects http already; defensive guard if the shape changes.
    throw new Error('emitter currently only supports stdio transports')
  }
  const command = JSON.stringify(config.transport.command)
  const args = JSON.stringify(config.transport.args ?? [])
  const envKeys = Object.keys(config.transport.env ?? {})
  const envBlock = envKeys.length
    ? `  env: {
${envKeys.map((k) => `    ${JSON.stringify(k)}: process.env[${JSON.stringify(k)}] ?? '',`).join('\n')}
    ...process.env,
  },`
    : '  env: process.env as Record<string, string>,'
  return `// Generated by \`glyph import mcp\` on ${new Date().toISOString()}
// Source: ${config.source}/${config.name}
//
// ⚠ Cost and risk tiers on each card were inferred by the MCP adapter from
// tool names and MCP annotations. Audit them before treating this server as
// production. See packages/adapters/mcp/src/index.ts for the heuristic.
import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
import { glyphsFromMcpClient } from '@glyphp/adapter-mcp'
import { GlyphServer } from '@glyphp/server'

const transport = new StdioClientTransport({
  command: ${command},
  args: ${args},
${envBlock}
})

const mcp = new Client({ name: 'glyph-bridge', version: '0.1.0' })
await mcp.connect(transport)

const glyphs = await glyphsFromMcpClient(mcp, { provider: 'mcp:${config.name}' })
const server = new GlyphServer({ port: ${port} })
for (const g of glyphs) server.register(g)
await server.start()

console.log('[glyph] ${config.name} bridge live on http://localhost:${port} with', glyphs.length, 'tools')
`
}

function renderPackageJson(config: McpServerConfig): string {
  return `${JSON.stringify(
    {
      name: `glyph-bridge-${config.name.replace(/[^a-z0-9-]+/gi, '-').toLowerCase()}`,
      version: '0.0.1',
      private: true,
      type: 'module',
      scripts: {
        dev: 'tsx server.ts',
      },
      dependencies: {
        '@glyphp/adapter-mcp': '^1.0.0',
        '@glyphp/server': '^1.1.0',
        '@modelcontextprotocol/sdk': '^1.0.0',
      },
      devDependencies: {
        tsx: '^4.11.0',
        typescript: '^5.4.0',
      },
    },
    null,
    2,
  )}\n`
}

function renderEnvExample(config: McpServerConfig): string {
  if (config.transport.kind !== 'stdio') return ''
  const keys = Object.keys(config.transport.env ?? {})
  if (keys.length === 0) {
    return `# No environment variables were declared in the source client config.\n`
  }
  return [
    '# Environment variables declared in the source client config.',
    `# Source: ${config.source}/${config.name}`,
    '# Values were intentionally NOT copied — fill them in here, then `source .env`.',
    '',
    ...keys.map((k) => `${k}=`),
    '',
  ].join('\n')
}

function renderReadme(
  config: McpServerConfig,
  port: number,
  cards: ImportedServer['cards'],
): string {
  const dangerCount = cards.filter((c) => c.riskTier === 'danger').length
  const cautionCount = cards.filter((c) => c.riskTier === 'caution').length
  const safeCount = cards.filter((c) => c.riskTier === 'safe').length
  return [
    `# \`${config.name}\` — Glyph bridge for an MCP server`,
    '',
    `Generated by \`glyph import mcp\` from **${config.source}**.`,
    '',
    '## Run',
    '',
    '```bash',
    'pnpm install',
    `pnpm run dev   # arranca el bridge en http://localhost:${port}`,
    '```',
    '',
    '## Tools',
    '',
    `${cards.length} tools (${safeCount} safe, ${cautionCount} caution, ${dangerCount} danger):`,
    '',
    ...cards.map(
      (c) =>
        `- \`${c.name}\` — risk: **${c.riskTier}**${c.requiresConfirmation ? ' • requires confirmation' : ''}`,
    ),
    '',
    '## ⚠ Review before production',
    '',
    'The MCP adapter inferred cost/risk from tool names and MCP annotations. ',
    'Verify each card whose risk is `danger` or `caution` matches your actual ',
    'security posture before connecting agents.',
    '',
  ].join('\n')
}

export async function emitTopLevelIndex(outDir: string, imported: ImportedServer[]): Promise<void> {
  const lines = [
    `# Glyph imports`,
    '',
    `Generated by \`glyph import mcp\` on ${new Date().toISOString()}.`,
    '',
    `${imported.length} MCP server(s) bridged. See \`IMPORT_REPORT.md\` for ` +
      'the full import log including any sources that were skipped.',
    '',
    '## Bridges',
    '',
    '| Name | Source | Port | Tools | Path |',
    '|---|---|--:|--:|---|',
    ...imported.map(
      (s) =>
        `| \`${s.config.name}\` | ${s.config.source} | ${s.port} | ${s.toolCount} | \`${s.outputDir}/\` |`,
    ),
    '',
  ]
  await writeFile(join(outDir, 'README.md'), lines.join('\n'), 'utf8')
}
